// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TremBomApi.Data;

#nullable disable

namespace TremBomApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526160959_CriarTabelaGruposMembros")]
    partial class CriarTabelaGruposMembros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TremBomApi.Models.Comentarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("comentario");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("TremBomApi.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LimiteMembros")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Privacidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("TremBomApi.Models.GrupoMembro", b =>
                {
                    b.Property<int>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GrupoId", "UsuarioId");

                    b.ToTable("GrupoMembros");
                });

            modelBuilder.Entity("TremBomApi.Models.Likes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateLike")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_like");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("likes");
                });

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT")
                        .HasColumnName("bairro");

                    b.Property<int?>("CEP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CEP");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("Cidade");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Dicas")
                        .HasColumnType("TEXT")
                        .HasColumnName("dicas");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.Property<string>("OqFazer")
                        .HasColumnType("TEXT")
                        .HasColumnName("oq_fazer");

                    b.Property<string>("PqVisitar")
                        .HasColumnType("TEXT")
                        .HasColumnName("pq_visitar");

                    b.Property<string>("Resumo")
                        .HasColumnType("TEXT")
                        .HasColumnName("resumo");

                    b.Property<DateTime?>("ResumoAtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Rua")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("rua");

                    b.HasKey("Id");

                    b.ToTable("locais");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_publicacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("publicacoes");
                });

            modelBuilder.Entity("TremBomApi.Models.PublicacaoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.ToTable("publicacoes_fotos");
                });

            modelBuilder.Entity("TremBomApi.Models.Seguidores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AlvoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SegueDesde")
                        .HasColumnType("TEXT")
                        .HasColumnName("segueDesde");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlvoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("seguidores");
                });

            modelBuilder.Entity("TremBomApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Aniversario")
                        .HasColumnType("TEXT")
                        .HasColumnName("aniversario");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("foto_perfil_url");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("genero");

                    b.Property<string>("IpRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.PrimitiveCollection<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preferencias");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("TremBomApi.Models.Comentarios", b =>
                {
                    b.HasOne("TremBomApi.Models.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Grupo", b =>
                {
                    b.HasOne("TremBomApi.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("TremBomApi.Models.GrupoMembro", b =>
                {
                    b.HasOne("TremBomApi.Models.Grupo", "Grupo")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("TremBomApi.Models.Likes", b =>
                {
                    b.HasOne("TremBomApi.Models.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.HasOne("TremBomApi.Models.Local", "Local")
                        .WithMany("Publicacoes")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.PublicacaoFoto", b =>
                {
                    b.HasOne("TremBomApi.Models.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");
                });

            modelBuilder.Entity("TremBomApi.Models.Seguidores", b =>
                {
                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("AlvoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario2")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("TremBomApi.Models.Grupo", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Navigation("Publicacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
