// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TremBomApi.Data;

#nullable disable

namespace TremBomApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519194914_AjustesTabela8")]
    partial class AjustesTabela8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<double>("AvaliacaoNota")
                        .HasColumnType("REAL")
                        .HasColumnName("avaliacao_nota");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT")
                        .HasColumnName("bairro");

                    b.Property<int?>("CEP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CEP");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("Cidade");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Dicas")
                        .HasColumnType("TEXT")
                        .HasColumnName("dicas");

                    b.Property<string>("HorarioTexto")
                        .HasColumnType("TEXT")
                        .HasColumnName("horario_texto");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url");

                    b.Property<string>("ImagemUrl2")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url_2");

                    b.Property<string>("ImagemUrl3")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url_3");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.Property<string>("OqFazer")
                        .HasColumnType("TEXT")
                        .HasColumnName("oq_fazer");

                    b.Property<string>("PqVisitar")
                        .HasColumnType("TEXT")
                        .HasColumnName("pq_visitar");

                    b.Property<string>("Rua")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("rua");

                    b.Property<int>("TotalComentarios")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_comentarios");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_likes");

                    b.HasKey("Id");

                    b.ToTable("locais");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("publicacoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("TokenLembrar")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_lembrar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sessoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Aniversario")
                        .HasColumnType("TEXT")
                        .HasColumnName("aniversario");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("foto_perfil_url");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.PrimitiveCollection<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preferencias");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("TremBomApi.Models.UsuarioPreferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Preferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("preferencia");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuarios_preferencias");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.HasOne("TremBomApi.Models.Local", "Local")
                        .WithMany("Publicacoes")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Sessao", b =>
                {
                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany("Sessoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.UsuarioPreferencia", b =>
                {
                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Navigation("Publicacoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Usuario", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
