// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TremBomApi.Data;

#nullable disable

namespace TremBomApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521210659_AjustesTabela14-1")]
    partial class AjustesTabela141
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TremBomApi.Models.Comentarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("comentario");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("TremBomApi.Models.Likes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("likes");
                });

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<double>("AvaliacaoNota")
                        .HasColumnType("REAL")
                        .HasColumnName("avaliacao_nota");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT")
                        .HasColumnName("bairro");

                    b.Property<int?>("CEP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CEP");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("Cidade");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Dicas")
                        .HasColumnType("TEXT")
                        .HasColumnName("dicas");

                    b.Property<string>("HorarioTexto")
                        .HasColumnType("TEXT")
                        .HasColumnName("horario_texto");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url");

                    b.Property<string>("ImagemUrl2")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url_2");

                    b.Property<string>("ImagemUrl3")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url_3");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.Property<string>("OqFazer")
                        .HasColumnType("TEXT")
                        .HasColumnName("oq_fazer");

                    b.Property<string>("PqVisitar")
                        .HasColumnType("TEXT")
                        .HasColumnName("pq_visitar");

                    b.Property<string>("Rua")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("rua");

                    b.Property<int>("TotalComentarios")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_comentarios");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_likes");

                    b.HasKey("Id");

                    b.ToTable("locais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AvaliacaoNota = 4.7999999999999998,
                            Bairro = "Pampulha",
                            CEP = 31365450,
                            Categoria = "Cultura e Arquitetura",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Famosa igreja projetada por Oscar Niemeyer, com painéis de Cândido Portinari, localizada na beira da Lagoa da Pampulha.",
                            Dicas = "Vá no fim da tarde para pegar o pôr do sol na lagoa.",
                            ImagemUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Igrejinha_de_S%C3%A3o_Francisco_de_Assis_6.jpeg/250px-Igrejinha_de_S%C3%A3o_Francisco_de_Assis_6.jpeg",
                            Latitude = -19.858499999999999,
                            Longitude = -43.979100000000003,
                            Nome = "Igreja São Francisco de Assis (Igrejinha da Pampulha)",
                            Numero = 3000,
                            OqFazer = "Tirar fotos da fachada, visitar o interior do museu e caminhar pela orla.",
                            PqVisitar = "É o principal cartão-postal de BH e Patrimônio Cultural da Humanidade pela UNESCO.",
                            Rua = "Avenida Otacílio Negrão de Lima",
                            TotalComentarios = 45,
                            TotalLikes = 150
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AvaliacaoNota = 4.9000000000000004,
                            Bairro = "Centro",
                            CEP = 30190056,
                            Categoria = "Gastronomia e Compras",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O coração da cultura mineira, com centenas de lojas vendendo queijos, doces, artesanatos e temperos.",
                            Dicas = "Costuma ficar muito cheio aos sábados de manhã. Vá de táxi ou aplicativo pois o estacionamento é disputado.",
                            ImagemUrl = "https://exemplo.com/mercado1.jpg",
                            Latitude = -19.922899999999998,
                            Longitude = -43.944400000000002,
                            Nome = "Mercado Central de Belo Horizonte",
                            Numero = 744,
                            OqFazer = "Provar o famoso fígado com jiló, comprar queijo canastra e doces caseiros.",
                            PqVisitar = "Eleito um dos melhores mercados do mundo, é o melhor lugar para sentir a verdadeira vibe mineira.",
                            Rua = "Avenida Augusto de Lima",
                            TotalComentarios = 98,
                            TotalLikes = 320
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            AvaliacaoNota = 4.7000000000000002,
                            Bairro = "Funcionários",
                            CEP = 30140010,
                            Categoria = "Lazer e Cultura",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Praça histórica cercada por belíssimos prédios públicos antigos que hoje formam o Circuito Cultural Praça da Liberdade.",
                            Dicas = "A visitação à maioria dos museus do circuito é gratuita.",
                            ImagemUrl = "https://www.quintoandar.com.br/guias/wp-content/uploads/2023/04/Praca-da-Liberdade-em-Belo-Horizonte-Foto-Shutterstock.jpg",
                            Latitude = -19.932300000000001,
                            Longitude = -43.938099999999999,
                            Nome = "Praça da Liberdade",
                            Numero = 1,
                            OqFazer = "Caminhar sob a alameda de palmeiras imperiais e visitar os museus ao redor.",
                            PqVisitar = "Une uma linda área verde com acesso direto aos melhores museus e centros culturais da cidade.",
                            Rua = "Praça da Liberdade",
                            TotalComentarios = 35,
                            TotalLikes = 210
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            AvaliacaoNota = 4.5999999999999996,
                            Bairro = "Mangabeiras",
                            CEP = 30210310,
                            Categoria = "Natureza e Vista",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Localizado em uma área de preservação, oferece uma vista panorâmica espetacular de toda a cidade de BH.",
                            Dicas = "Leve um agasalho, pois costuma ventilar bastante e fazer frio lá em cima.",
                            ImagemUrl = "https://offloadmedia.feverup.com/belohorizontesecreto.com/wp-content/uploads/2023/08/21122832/mirantes-em-belo-horizonte-1024x683.jpg",
                            Latitude = -19.9482,
                            Longitude = -43.916800000000002,
                            Nome = "Mirante do Mangabeiras",
                            Numero = 100,
                            OqFazer = "Apreciar a vista das plataformas de madeira e tirar fotos panorâmicas.",
                            PqVisitar = "É o ponto mais alto e bonito para ver a imensidão de Belo Horizonte lá do alto.",
                            Rua = "Rua Pedro José Pardo",
                            TotalComentarios = 29,
                            TotalLikes = 185
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            AvaliacaoNota = 4.7000000000000002,
                            Bairro = "São José",
                            CEP = 31275000,
                            Categoria = "Esportes e Eventos",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O gigante da Pampulha, palco histórico do futebol mineiro e grandes shows internacionais.",
                            Dicas = "A esplanada do Mineirão é enorme e excelente para passar a tarde com crianças e pets.",
                            ImagemUrl = "https://historiadofutebol.com/blog/wp-content/uploads/2013/11/092-001-500x330.jpg",
                            Latitude = -19.8659,
                            Longitude = -43.970999999999997,
                            Nome = "Minerão (Estádio Governador Magalhães Pinto)",
                            Numero = 1001,
                            OqFazer = "Visitar o Museu do Futebol Mineiro e andar de skate ou patins na esplanada.",
                            PqVisitar = "Item indispensável para quem ama futebol e quer conhecer o templo do esporte em Minas.",
                            Rua = "Avenida Antônio Abrahão Caram",
                            TotalComentarios = 60,
                            TotalLikes = 250
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            AvaliacaoNota = 4.5,
                            Bairro = "Centro",
                            CEP = 30130003,
                            Categoria = "Natureza e Parque",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O mais antigo parque ambiental de BH, localizado bem no centro da cidade, um verdadeiro refúgio verde.",
                            Dicas = "O parque abriga o tradicional Teatro Francisco Nunes, vale checar a programação.",
                            ImagemUrl = "https://portalbelohorizonte.com.br/sites/default/files/arquivos/ao-ar-livre-e-esportes/2021-11/foto-pbh.jpg",
                            Latitude = -19.924199999999999,
                            Longitude = -43.930599999999998,
                            Nome = "Parque Municipal Américo Renné Giannetti",
                            Numero = 1377,
                            OqFazer = "Andar de barco a remo nas lagoas, fazer piquenique e ver os pequenos monumentos.",
                            PqVisitar = "Ideal para desacelerar e curtir a natureza sem sair da região central da capital.",
                            Rua = "Avenida Afonso Pena",
                            TotalComentarios = 22,
                            TotalLikes = 140
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            AvaliacaoNota = 4.7999999999999998,
                            Bairro = "Mangabeiras",
                            CEP = 30210130,
                            Categoria = "Lazer e Vista",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Localizada nas altas do bairro Mangabeiras, ganhou esse nome após a visita do Papa João Paulo II em 1980.",
                            Dicas = "Perfeito para levar uma canga, lanche e fazer um piquenique no final de semana.",
                            ImagemUrl = "https://portalbelohorizonte.com.br/sites/default/files/arquivos/ao-ar-livre-e-esportes/2021-11/praca-do-papa_qu4rto-studio-0056-1_0.jpg",
                            Latitude = -19.9453,
                            Longitude = -43.914200000000001,
                            Nome = "Praça do Papa",
                            Numero = 1,
                            OqFazer = "Sentar no gramado, contemplar o horizonte e descansar.",
                            PqVisitar = "Famosa pela frase do Papa: 'Que belo horizonte!'. A energia e a paz do lugar são incríveis.",
                            Rua = "Praça Israel Pinheiro",
                            TotalComentarios = 40,
                            TotalLikes = 280
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            AvaliacaoNota = 4.9000000000000004,
                            Bairro = "Inhotim",
                            CEP = 35460000,
                            Categoria = "Arte e Botânica",
                            Cidade = "Brumadinho",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Embora fique em Brumadinho (região metropolitana), é a principal extensão turística cultural de quem visita BH. Maior museu a céu aberto do mundo.",
                            Dicas = "Use sapatos muito confortáveis, o museu é gigante e você vai andar bastante.",
                            ImagemUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVYgiX-foSy-CNzygiQBc9Z95TOzdbfFNAWA&s",
                            Latitude = -20.124099999999999,
                            Longitude = -44.220100000000002,
                            Nome = "Inhotim (Instituto Contemporâneo)",
                            Numero = 20,
                            OqFazer = "Caminhar pelos jardins botânicos espetaculares e entrar nas galerias de arte contemporânea.",
                            PqVisitar = "Referência internacional, une perfeitamente arte contemporânea de ponta com paisagismo exuberante.",
                            Rua = "Rua B",
                            TotalComentarios = 150,
                            TotalLikes = 500
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            AvaliacaoNota = 4.5999999999999996,
                            Bairro = "Centro",
                            CEP = 30160041,
                            Categoria = "Cultura e Teatro",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Grande centro cultural no centro de BH que recebe shows, peças de teatro, cinema e exposições de arte.",
                            Dicas = "Fique de olho no site oficial deles, pois muitos eventos têm ingressos a preços populares.",
                            ImagemUrl = "https://www.minasgerais.com.br/imagens/atracoes/1542284694Euy5sOet5H.jpg",
                            Latitude = -19.923400000000001,
                            Longitude = -43.9392,
                            Nome = "Sesc Palladium",
                            Numero = 1046,
                            OqFazer = "Assistir a espetáculos musicais, peças de teatro ou mostras de cinema alternativo.",
                            PqVisitar = "Um dos espaços culturais mais modernos e ativos localizados no hipercentro de BH.",
                            Rua = "Rua Rio de Janeiro",
                            TotalComentarios = 14,
                            TotalLikes = 95
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            AvaliacaoNota = 4.2999999999999998,
                            Bairro = "Mangabeiras",
                            CEP = 30210300,
                            Categoria = "Curiosidade Local",
                            Cidade = "Belo Horizonte",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Famosa rua ladeira acima onde os carros, quando deixados em ponto morto, parecem subir a rua sozinhos devido a uma ilusão de ótica.",
                            Dicas = "Faça o teste com cuidado e pisca-alerta ligado para avisar outros motoristas.",
                            ImagemUrl = "https://media-cdn.tripadvisor.com/media/photo-s/07/5c/ec/4e/rua-do-amendoim.jpg",
                            Latitude = -19.943100000000001,
                            Longitude = -43.914900000000003,
                            Nome = "Rua do Amendoim",
                            Numero = 10,
                            OqFazer = "Colocar o carro em ponto morto (desligado) e testar a famosa ilusão de ótica.",
                            PqVisitar = "É um clássico folclórico de mistério e diversão que diverte turistas e moradores há décadas.",
                            Rua = "Rua Professor Otávio Coelho Magalhães",
                            TotalComentarios = 55,
                            TotalLikes = 110
                        });
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_publicacao");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("publicacoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Seguidores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AlvoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SegueDesde")
                        .HasColumnType("TEXT")
                        .HasColumnName("segueDesde");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlvoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("seguidores");
                });

            modelBuilder.Entity("TremBomApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Aniversario")
                        .HasColumnType("TEXT")
                        .HasColumnName("aniversario");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("foto_perfil_url");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("genero");

                    b.Property<string>("IpRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.PrimitiveCollection<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preferencias");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("TremBomApi.Models.Comentarios", b =>
                {
                    b.HasOne("TremBomApi.Models.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Likes", b =>
                {
                    b.HasOne("TremBomApi.Models.Publicacao", "Publicacao")
                        .WithMany()
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.HasOne("TremBomApi.Models.Local", "Local")
                        .WithMany("Publicacoes")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Seguidores", b =>
                {
                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("AlvoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario2")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Navigation("Publicacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
