// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TremBomApi.Data;

#nullable disable

namespace TremBomApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424180519_PopularNovosCampos")]
    partial class PopularNovosCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<double>("AvaliacaoNota")
                        .HasColumnType("REAL")
                        .HasColumnName("avaliacao_nota");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Dicas")
                        .HasColumnType("TEXT")
                        .HasColumnName("dicas");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("endereco");

                    b.Property<string>("HorarioTexto")
                        .HasColumnType("TEXT")
                        .HasColumnName("horario_texto");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url");

                    b.Property<string>("ImagemUrl2")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url_2");

                    b.Property<string>("ImagemUrl3")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url_3");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("OqFazer")
                        .HasColumnType("TEXT")
                        .HasColumnName("oq_fazer");

                    b.Property<string>("PqVisitar")
                        .HasColumnType("TEXT")
                        .HasColumnName("pq_visitar");

                    b.Property<int>("TotalComentarios")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_comentarios");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_likes");

                    b.HasKey("Id");

                    b.ToTable("locais");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Ativo = true,
                            AvaliacaoNota = 4.7999999999999998,
                            Categoria = "Edifício Gastronômico",
                            DataCadastro = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O clássico: fígado com jiló, queijos premiados e o melhor doce de leite.",
                            Dicas = "Vá cedo nos finais de semana para evitar multidões e não deixe de visitar a loja de queijos do Mário.",
                            Endereco = "Av. Augusto de Lima, 744 - Centro, Belo Horizonte",
                            HorarioTexto = "Segunda a Sábado: 07:00 - 18:00",
                            ImagemUrl = "https://viajenaweb.com/wp-content/uploads/2016/12/O-que-fazer-no-Mercado-Central-de-Belo-Horizonte-768x432.jpg.webp",
                            Nome = "Mercado Central",
                            OqFazer = "Comprar queijos, doces, artesanatos e provar o famoso fígado com jiló.",
                            PqVisitar = "É considerado um dos melhores mercados do mundo e a alma da cultura mineira.",
                            TotalComentarios = 0,
                            TotalLikes = 0
                        },
                        new
                        {
                            Id = 102,
                            Ativo = true,
                            AvaliacaoNota = 3.7999999999999998,
                            Categoria = "Edifício Gastronômico",
                            DataCadastro = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cozinha de raiz, bares artesanais e um ambiente retrô industrial incrível.",
                            Dicas = "O segundo andar é onde a 'magia' acontece. Experimente o Gin da Lamparina.",
                            Endereco = "Rua Rio de Janeiro, 600 - Centro, Belo Horizonte",
                            HorarioTexto = "Quinta-feira: 08:00 - 18:00",
                            ImagemUrl = "https://www.hojeemdia.com.br/image/policy:1.992457.1702919772:1702919772/image.jpg?f=2x1&w=1200",
                            ImagemUrl2 = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/3f/e2/0d/mercado-novo.jpg",
                            ImagemUrl3 = "https://bhaz.com.br/wp-content/uploads/2019/07/mercado-novo-bh-1.jpg",
                            Nome = "Mercado Novo",
                            OqFazer = "Visitar bares de cerveja artesanal, destilarias e comer comida de raiz.",
                            PqVisitar = "Um espaço que une o retrô industrial com o que há de mais moderno na gastronomia de BH.",
                            TotalComentarios = 0,
                            TotalLikes = 0
                        },
                        new
                        {
                            Id = 103,
                            Ativo = true,
                            AvaliacaoNota = 4.5,
                            Categoria = "Edifício Gastronômico",
                            DataCadastro = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Varandas icônicas e bares históricos no centro de BH.",
                            Dicas = "A Cantina do Lucas é patrimônio histórico e fica no térreo.",
                            Endereco = "Rua da Bahia, 1148 - Centro, Belo Horizonte",
                            HorarioTexto = "Terça a Domingo: 11:00 - 00:00",
                            ImagemUrl = "https://resize.casapino.com.br/?u=https://cms-bomgourmet.s3.amazonaws.com/bomgourmet/2018/10/201810/maletta-belo-horizonte-varanda-20f288a0.jpg&w=661",
                            Nome = "Edifício Maletta",
                            OqFazer = "Tomar um café, visitar sebos e curtir a noite nas varandas do segundo andar.",
                            PqVisitar = "Ponto de encontro boêmio histórico de intelectuais e artistas de Minas.",
                            TotalComentarios = 0,
                            TotalLikes = 0
                        },
                        new
                        {
                            Id = 104,
                            Ativo = true,
                            AvaliacaoNota = 4.9000000000000004,
                            Categoria = "Bar",
                            DataCadastro = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "O bar mais antigo de BH, patrimônio do bairro Santa Tereza.",
                            Dicas = "Chegue antes do pôr do sol para garantir uma mesa na calçada.",
                            Endereco = "Rua Almeida Castro, 161 - Santa Tereza, Belo Horizonte",
                            HorarioTexto = "Todos os dias: 09:00 - 22:00",
                            ImagemUrl = "https://folhadesetelagoas.com.br/images/noticias/190/9f40c1539471322fcf360b2a9be33a36.jpeg",
                            Nome = "Bar do Orlando",
                            OqFazer = "Tomar cerveja gelada no copo americano e comer o petisco de linguiça.",
                            PqVisitar = "Fundado em 1919, é o bar mais antigo em funcionamento contínuo de BH.",
                            TotalComentarios = 0,
                            TotalLikes = 0
                        },
                        new
                        {
                            Id = 105,
                            Ativo = true,
                            AvaliacaoNota = 4.7000000000000002,
                            Categoria = "Bar",
                            DataCadastro = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cervejaria local com clima de calçada e muita mineiridade.",
                            Dicas = "O local é pequeno e a galera fica na rua, o clima é super descontraído.",
                            Endereco = "Rua Juramento, 202 - Pompeia, Belo Horizonte",
                            HorarioTexto = "Quarta a Domingo: 17:00 - 23:00",
                            ImagemUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/04/71/ad/img-20181005-wa0018-largejpg.jpg?w=1000&h=-1&s=1",
                            Nome = "Juramento 202",
                            OqFazer = "Degustar chopes artesanais da Viela e ouvir música brasileira.",
                            PqVisitar = "Representa o renascimento dos bares de bairro com foco em qualidade artesanal.",
                            TotalComentarios = 0,
                            TotalLikes = 0
                        },
                        new
                        {
                            Id = 106,
                            Ativo = true,
                            AvaliacaoNota = 4.5999999999999996,
                            Categoria = "Pizzaria",
                            DataCadastro = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pizzaria charmosa em um casarão dos anos 30 com vista panorâmica.",
                            Dicas = "Tente pegar um lugar na varanda para ver as luzes de BH à noite.",
                            Endereco = "Rua Patrocínio, 1 - Carlos Prates, Belo Horizonte",
                            HorarioTexto = "Terça a Domingo: 18:00 - 23:30",
                            ImagemUrl = "https://andadireito.com.br/wp-content/uploads/2025/12/Forno-da-Saudade-5.png",
                            Nome = "Forno da Saudade",
                            OqFazer = "Comer pizzas individuais de longa fermentação com vista para a cidade.",
                            PqVisitar = "A localização em um casarão antigo no alto de uma colina proporciona uma experiência única.",
                            TotalComentarios = 0,
                            TotalLikes = 0
                        });
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("publicacoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("TokenLembrar")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_lembrar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sessoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("foto_perfil_url");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_completo");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("TermosAceitosEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("termos_aceitos_em");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("TremBomApi.Models.UsuarioPreferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Preferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("preferencia");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuarios_preferencias");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.HasOne("TremBomApi.Models.Local", "Local")
                        .WithMany("Publicacoes")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Sessao", b =>
                {
                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany("Sessoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.UsuarioPreferencia", b =>
                {
                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany("Preferencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Navigation("Publicacoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Usuario", b =>
                {
                    b.Navigation("Preferencias");

                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
