// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TremBomApi.Data;

#nullable disable

namespace TremBomApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422151237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TremBomApi.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("publicacao_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("texto");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("TotalComentarios")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_comentarios");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_likes");

                    b.HasKey("Id");

                    b.ToTable("locais");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT")
                        .HasColumnName("feedback");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("local_id");

                    b.Property<string>("LocalNome")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_nome");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating");

                    b.Property<int>("TotalComentarios")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_comentarios");

                    b.Property<int>("TotalCompartilhamentos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_compartilhamentos");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_likes");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("publicacoes");
                });

            modelBuilder.Entity("TremBomApi.Models.PublicacaoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("foto_url");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordem");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("publicacao_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.ToTable("publicacoes_fotos");
                });

            modelBuilder.Entity("TremBomApi.Models.PublicacaoLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataLike")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_like");

                    b.Property<int>("PublicacaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("publicacao_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("publicacoes_likes");
                });

            modelBuilder.Entity("TremBomApi.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("TokenLembrar")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_lembrar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sessoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("foto_perfil_url");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_completo");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("TermosAceitosEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("termos_aceitos_em");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("TremBomApi.Models.UsuarioPreferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Preferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("preferencia");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuarios_preferencias");
                });

            modelBuilder.Entity("TremBomApi.Models.Comentario", b =>
                {
                    b.HasOne("TremBomApi.Models.Publicacao", "Publicacao")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.HasOne("TremBomApi.Models.Local", "Local")
                        .WithMany("Publicacoes")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.PublicacaoFoto", b =>
                {
                    b.HasOne("TremBomApi.Models.Publicacao", "Publicacao")
                        .WithMany("Fotos")
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");
                });

            modelBuilder.Entity("TremBomApi.Models.PublicacaoLike", b =>
                {
                    b.HasOne("TremBomApi.Models.Publicacao", "Publicacao")
                        .WithMany("Likes")
                        .HasForeignKey("PublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Sessao", b =>
                {
                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany("Sessoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.UsuarioPreferencia", b =>
                {
                    b.HasOne("TremBomApi.Models.Usuario", "Usuario")
                        .WithMany("Preferencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TremBomApi.Models.Local", b =>
                {
                    b.Navigation("Publicacoes");
                });

            modelBuilder.Entity("TremBomApi.Models.Publicacao", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Fotos");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("TremBomApi.Models.Usuario", b =>
                {
                    b.Navigation("Preferencias");

                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
